2024-02-14T05:27:42.5785446Z TRACE:: Config.Get(): Configuration key not found. Key: version-id - Using default value: 
2024-02-14T05:27:42.6368320Z TRACE:: Config.Get(): Configuration key not found. Key: cache-location - Using default value: 
2024-02-14T05:27:42.6375548Z TRACE:: Engine.Main(): LEAN ALGORITHMIC TRADING ENGINE v2.5.0.0 Mode: DEBUG (64bit) Host: LAPTOP-BC2TTKVT
2024-02-14T05:27:42.6436020Z TRACE:: Engine.Main(): Started 5:27 AM
2024-02-14T05:27:42.6535030Z TRACE:: Config.Get(): Configuration key not found. Key: lean-manager-type - Using default value: LocalLeanManager
2024-02-14T05:27:42.6946360Z TRACE:: JobQueue.NextJob(): Selected /LeanCLI/main.py
2024-02-14T05:27:42.8646469Z TRACE:: Config.GetValue(): scheduled-event-leaky-bucket-capacity - Using default value: 120
2024-02-14T05:27:42.8652816Z TRACE:: Config.GetValue(): scheduled-event-leaky-bucket-time-interval-minutes - Using default value: 1440
2024-02-14T05:27:42.8659275Z TRACE:: Config.GetValue(): scheduled-event-leaky-bucket-refill-amount - Using default value: 18
2024-02-14T05:27:42.8669024Z TRACE:: Config.GetValue(): maximum-chart-series - Using default value: 30
2024-02-14T05:27:42.8689277Z TRACE:: Config.GetValue(): storage-limit - Using default value: 10737418240
2024-02-14T05:27:42.8696358Z TRACE:: Config.GetValue(): storage-permissions - Using default value: 3
2024-02-14T05:27:42.8709318Z TRACE:: Config.Get(): Configuration key not found. Key: optimization-id - Using default value: 
2024-02-14T05:27:42.8716971Z TRACE:: Config.Get(): Configuration key not found. Key: backtest-name - Using default value: local
2024-02-14T05:27:42.8861027Z TRACE:: Config.Get(): Configuration key not found. Key: data-channel - Using default value: 
2024-02-14T05:27:42.8867012Z TRACE:: Config.Get(): Configuration key not found. Key: job-organization-id - Using default value: 
2024-02-14T05:27:42.8873017Z TRACE:: Config.Get(): Configuration key not found. Key: python-venv - Using default value: 
2024-02-14T05:27:42.8878399Z TRACE:: Config.Get(): Configuration key not found. Key: out-of-sample-max-end-date - Using default value: 
2024-02-14T05:27:42.8887728Z TRACE:: Config.GetValue(): out-of-sample-days - Using default value: 0
2024-02-14T05:27:42.8917798Z TRACE:: Config.Get(): Configuration key not found. Key: data-permission-manager - Using default value: DataPermissionManager
2024-02-14T05:27:42.9524320Z TRACE:: Config.GetValue(): zip-data-cache-provider - Using default value: 10
2024-02-14T05:27:42.9571253Z TRACE:: Config.Get(): Configuration key not found. Key: fundamental-data-provider - Using default value: CoarseFundamentalDataProvider
2024-02-14T05:27:42.9683037Z TRACE:: AlgorithmManager.CreateTokenBucket(): Initializing LeakyBucket: Capacity: 120 RefillAmount: 18 TimeInterval: 1440
2024-02-14T05:27:42.9698962Z TRACE:: Config.GetValue(): algorithm-manager-time-loop-maximum - Using default value: 20
2024-02-14T05:27:43.0131129Z TRACE:: Engine.Run(): Resource limits '0' CPUs. 2147483647 MB RAM.
2024-02-14T05:27:43.0149911Z TRACE:: TextSubscriptionDataSourceReader.SetCacheSize(): Setting cache size to 71582788 items
2024-02-14T05:27:43.1294817Z TRACE:: Config.GetValue(): downloader-data-update-period - Using default value: 7
2024-02-14T05:27:43.8358636Z TRACE:: DebuggerHelper.Initialize(): initializing python...
2024-02-14T05:27:43.8367526Z TRACE:: PythonInitializer.Initialize(): start...
2024-02-14T05:27:45.7901063Z TRACE:: PythonInitializer.Initialize(): ended
2024-02-14T05:27:45.7942845Z TRACE:: DebuggerHelper.Initialize(): python initialization done
2024-02-14T05:27:45.7956041Z TRACE:: DebuggerHelper.Initialize(): starting...
2024-02-14T05:27:45.8043767Z TRACE:: DebuggerHelper.Initialize(): waiting for PTVSD debugger to attach at localhost:5678...
2024-02-14T05:27:58.9185308Z TRACE:: DebuggerHelper.Initialize(): started
2024-02-14T05:27:58.9198551Z TRACE:: Config.GetValue(): algorithm-creation-timeout - Using default value: 90
2024-02-14T05:27:58.9304985Z TRACE:: AlgorithmPythonWrapper(): Python version 3.8.16 (default, Jan 17 2023, 23:21:03) 
[GCC 11.2.0]: Importing python module main
2024-02-14T05:28:12.5553912Z TRACE:: AlgorithmPythonWrapper(): main successfully imported.
2024-02-14T05:28:12.5616774Z TRACE:: AlgorithmPythonWrapper(): Creating IAlgorithm instance.
2024-02-14T05:28:12.7425607Z TRACE:: LocalObjectStore.Initialize(): Storage Root: /Storage. StorageFileCount 9999999. StorageLimit 10240MB
2024-02-14T05:28:12.7532458Z TRACE:: Config.GetValue(): zip-data-cache-provider - Using default value: 10
2024-02-14T05:28:12.7610172Z TRACE:: HistoryProviderManager.Initialize(): history providers [SubscriptionDataReaderHistoryProvider]
2024-02-14T05:28:12.7639589Z TRACE:: BacktestingSetupHandler.Setup(): Setting up job: UID: 255804, PID: 388644080, Version: 2.5.0.0, Source: WebIDE
2024-02-14T05:28:12.7731260Z TRACE:: Config.Get(): Configuration key not found. Key: security-data-feeds - Using default value: 
2024-02-14T05:28:12.9219258Z TRACE:: Config.GetValue(): data-feed-workers-count - Using default value: 16
2024-02-14T05:28:12.9262703Z TRACE:: Config.GetValue(): data-feed-max-work-weight - Using default value: 400
2024-02-14T05:28:12.9267561Z TRACE:: WeightedWorkScheduler(): will use 16 workers and MaxWorkWeight is 400
2024-02-14T05:28:13.4520983Z TRACE:: BacktestingResultHandler(): Sample Period Set: 104.40
2024-02-14T05:28:13.4561003Z TRACE:: Config.GetValue(): forward-console-messages - Using default value: True
2024-02-14T05:28:13.6644243Z ERROR:: Engine.Run(): During the algorithm initialization, the following exception has occurred: module 'tensorflow' has no attribute 'get_default_graph'
  at Initialize
    self.graph = tf.get_default_graph()
   at Python.Runtime.PythonException.ThrowLastAsClrException()
   at Python.Runtime.PyObject.Invoke(PyTuple args in main.py: line 232
 module 'tensorflow' has no attribute 'get_default_graph'
2024-02-14T05:28:13.6657783Z TRACE:: JOB HANDLERS:
         DataFeed:             QuantConnect.Lean.Engine.DataFeeds.FileSystemDataFeed
         Setup:                QuantConnect.Lean.Engine.Setup.BacktestingSetupHandler
         RealTime:             QuantConnect.Lean.Engine.RealTime.BacktestingRealTimeHandler
         Results:              QuantConnect.Lean.Engine.Results.BacktestingResultHandler
         Transactions:         QuantConnect.Lean.Engine.TransactionHandlers.BacktestingTransactionHandler
         Object Store:         QuantConnect.Lean.Engine.Storage.LocalObjectStore
         History Provider:     QuantConnect.Lean.Engine.HistoricalData.HistoryProviderManager
         Brokerage:            QuantConnect.Brokerages.Backtesting.BacktestingBrokerage
         Data Provider:        QuantConnect.Lean.Engine.DataFeeds.DefaultDataProvider

2024-02-14T05:28:13.6664511Z TRACE:: FileSystemDataFeed.Exit(): Start. Setting cancellation token...
2024-02-14T05:28:13.6689709Z TRACE:: FileSystemDataFeed.Exit(): Exit Finished.
2024-02-14T05:28:13.6698131Z TRACE:: BacktestingResultHandler.Exit(): starting...
2024-02-14T05:28:13.6974162Z TRACE:: BacktestingResultHandler.Exit(): Saving logs...
2024-02-14T05:28:13.7032971Z ERROR:: During the algorithm initialization, the following exception has occurred: module 'tensorflow' has no attribute 'get_default_graph'
  at Initialize
    self.graph = tf.get_default_graph()
   at Python.Runtime.PythonException.ThrowLastAsClrException()
   at Python.Runtime.PyObject.Invoke(PyTuple args in main.py: line 232
 module 'tensorflow' has no attribute 'get_default_graph'
 module 'tensorflow' has no attribute 'get_default_graph'
  at Initialize
    self.graph = tf.get_default_graph()
   at Python.Runtime.PythonException.ThrowLastAsClrException()
   at Python.Runtime.PyObject.Invoke(PyTuple args in main.py: line 232
 module 'tensorflow' has no attribute 'get_default_graph'
2024-02-14T05:28:13.7036048Z TRACE:: Debug: 123
2024-02-14T05:28:13.7037441Z TRACE:: StopSafely(): Waiting for 'Result Thread' thread to stop...
2024-02-14T05:28:13.7043877Z TRACE:: Debug: Your log was successfully created and can be retrieved from: /Results/1267098963-log.txt
2024-02-14T05:28:13.7056329Z TRACE:: BacktestingResultHandler.Run(): Ending Thread...
2024-02-14T05:28:13.8556872Z TRACE:: 
STATISTICS:: OrderListHash d41d8cd98f00b204e9800998ecf8427e
2024-02-14T05:28:13.8560529Z TRACE:: BacktestingResultHandler.SendAnalysisResult(): Processed final packet
2024-02-14T05:28:13.8568839Z TRACE:: Engine.Run(): Disconnecting from brokerage...
2024-02-14T05:28:13.8574542Z TRACE:: Engine.Run(): Disposing of setup handler...
2024-02-14T05:28:13.8579610Z TRACE:: Engine.Main(): Analysis Completed and Results Posted.
2024-02-14T05:28:13.8594168Z TRACE:: StopSafely(): Waiting for '' thread to stop...
2024-02-14T05:28:13.8641574Z TRACE:: DataMonitor.GenerateReport():
DATA USAGE:: Total data requests 1
DATA USAGE:: Succeeded data requests 1
DATA USAGE:: Failed data requests 0
DATA USAGE:: Failed data requests percentage 0%
DATA USAGE:: Total universe data requests 0
DATA USAGE:: Succeeded universe data requests 0
DATA USAGE:: Failed universe data requests 0
DATA USAGE:: Failed universe data requests percentage 0%
2024-02-14T05:28:13.8767789Z TRACE:: Engine.Main(): Packet removed from queue: 1267098963
2024-02-14T05:28:13.8772034Z TRACE:: LeanEngineSystemHandlers.Dispose(): start...
2024-02-14T05:28:13.8778825Z TRACE:: LeanEngineSystemHandlers.Dispose(): Disposed of system handlers.
2024-02-14T05:28:13.8784033Z TRACE:: LeanEngineAlgorithmHandlers.Dispose(): start...
2024-02-14T05:28:13.8829415Z TRACE:: LeanEngineAlgorithmHandlers.Dispose(): Disposed of algorithm handlers.
