2024-02-14T05:34:14.3425811Z TRACE:: Config.Get(): Configuration key not found. Key: version-id - Using default value: 
2024-02-14T05:34:14.3658560Z TRACE:: Config.Get(): Configuration key not found. Key: cache-location - Using default value: 
2024-02-14T05:34:14.3668169Z TRACE:: Engine.Main(): LEAN ALGORITHMIC TRADING ENGINE v2.5.0.0 Mode: DEBUG (64bit) Host: LAPTOP-BC2TTKVT
2024-02-14T05:34:14.3737853Z TRACE:: Engine.Main(): Started 5:34 AM
2024-02-14T05:34:14.3867585Z TRACE:: Config.Get(): Configuration key not found. Key: lean-manager-type - Using default value: LocalLeanManager
2024-02-14T05:34:14.4308509Z TRACE:: JobQueue.NextJob(): Selected /LeanCLI/main.py
2024-02-14T05:34:14.5749515Z TRACE:: Config.GetValue(): scheduled-event-leaky-bucket-capacity - Using default value: 120
2024-02-14T05:34:14.5754532Z TRACE:: Config.GetValue(): scheduled-event-leaky-bucket-time-interval-minutes - Using default value: 1440
2024-02-14T05:34:14.5758657Z TRACE:: Config.GetValue(): scheduled-event-leaky-bucket-refill-amount - Using default value: 18
2024-02-14T05:34:14.5763006Z TRACE:: Config.GetValue(): maximum-chart-series - Using default value: 30
2024-02-14T05:34:14.5779601Z TRACE:: Config.GetValue(): storage-limit - Using default value: 10737418240
2024-02-14T05:34:14.5787752Z TRACE:: Config.GetValue(): storage-permissions - Using default value: 3
2024-02-14T05:34:14.5792593Z TRACE:: Config.Get(): Configuration key not found. Key: optimization-id - Using default value: 
2024-02-14T05:34:14.5798768Z TRACE:: Config.Get(): Configuration key not found. Key: backtest-name - Using default value: local
2024-02-14T05:34:14.5933296Z TRACE:: Config.Get(): Configuration key not found. Key: data-channel - Using default value: 
2024-02-14T05:34:14.5938421Z TRACE:: Config.Get(): Configuration key not found. Key: job-organization-id - Using default value: 
2024-02-14T05:34:14.5943334Z TRACE:: Config.Get(): Configuration key not found. Key: python-venv - Using default value: 
2024-02-14T05:34:14.5947462Z TRACE:: Config.Get(): Configuration key not found. Key: out-of-sample-max-end-date - Using default value: 
2024-02-14T05:34:14.5951277Z TRACE:: Config.GetValue(): out-of-sample-days - Using default value: 0
2024-02-14T05:34:14.5978666Z TRACE:: Config.Get(): Configuration key not found. Key: data-permission-manager - Using default value: DataPermissionManager
2024-02-14T05:34:14.6565446Z TRACE:: Config.GetValue(): zip-data-cache-provider - Using default value: 10
2024-02-14T05:34:14.6613242Z TRACE:: Config.Get(): Configuration key not found. Key: fundamental-data-provider - Using default value: CoarseFundamentalDataProvider
2024-02-14T05:34:14.6706787Z TRACE:: AlgorithmManager.CreateTokenBucket(): Initializing LeakyBucket: Capacity: 120 RefillAmount: 18 TimeInterval: 1440
2024-02-14T05:34:14.6720525Z TRACE:: Config.GetValue(): algorithm-manager-time-loop-maximum - Using default value: 20
2024-02-14T05:34:14.7069848Z TRACE:: Engine.Run(): Resource limits '0' CPUs. 2147483647 MB RAM.
2024-02-14T05:34:14.7085996Z TRACE:: TextSubscriptionDataSourceReader.SetCacheSize(): Setting cache size to 71582788 items
2024-02-14T05:34:14.8232737Z TRACE:: Config.GetValue(): downloader-data-update-period - Using default value: 7
2024-02-14T05:34:15.3972978Z TRACE:: DebuggerHelper.Initialize(): initializing python...
2024-02-14T05:34:15.3982791Z TRACE:: PythonInitializer.Initialize(): start...
2024-02-14T05:34:17.2419087Z TRACE:: PythonInitializer.Initialize(): ended
2024-02-14T05:34:17.2424273Z TRACE:: DebuggerHelper.Initialize(): python initialization done
2024-02-14T05:34:17.2429345Z TRACE:: DebuggerHelper.Initialize(): starting...
2024-02-14T05:34:17.2432871Z TRACE:: DebuggerHelper.Initialize(): waiting for PTVSD debugger to attach at localhost:5678...
2024-02-14T05:34:29.6161143Z TRACE:: DebuggerHelper.Initialize(): started
2024-02-14T05:34:29.6172497Z TRACE:: Config.GetValue(): algorithm-creation-timeout - Using default value: 90
2024-02-14T05:34:29.6267700Z TRACE:: AlgorithmPythonWrapper(): Python version 3.8.16 (default, Jan 17 2023, 23:21:03) 
[GCC 11.2.0]: Importing python module main
2024-02-14T05:34:43.0967655Z TRACE:: AlgorithmPythonWrapper(): main successfully imported.
2024-02-14T05:34:43.1051224Z TRACE:: AlgorithmPythonWrapper(): Creating IAlgorithm instance.
2024-02-14T05:34:43.2995717Z TRACE:: LocalObjectStore.Initialize(): Storage Root: /Storage. StorageFileCount 9999999. StorageLimit 10240MB
2024-02-14T05:34:43.3149293Z TRACE:: Config.GetValue(): zip-data-cache-provider - Using default value: 10
2024-02-14T05:34:43.3246879Z TRACE:: HistoryProviderManager.Initialize(): history providers [SubscriptionDataReaderHistoryProvider]
2024-02-14T05:34:43.3353365Z TRACE:: BacktestingSetupHandler.Setup(): Setting up job: UID: 255804, PID: 388644080, Version: 2.5.0.0, Source: WebIDE
2024-02-14T05:34:43.3551744Z TRACE:: Config.Get(): Configuration key not found. Key: security-data-feeds - Using default value: 
2024-02-14T05:34:43.5312372Z TRACE:: Config.GetValue(): data-feed-workers-count - Using default value: 16
2024-02-14T05:34:43.5349746Z TRACE:: Config.GetValue(): data-feed-max-work-weight - Using default value: 400
2024-02-14T05:34:43.5352905Z TRACE:: WeightedWorkScheduler(): will use 16 workers and MaxWorkWeight is 400
2024-02-14T05:34:44.0567041Z TRACE:: BacktestingResultHandler(): Sample Period Set: 104.40
2024-02-14T05:34:44.0609854Z TRACE:: Config.GetValue(): forward-console-messages - Using default value: True
2024-02-14T05:34:44.2691952Z ERROR:: Engine.Run(): During the algorithm initialization, the following exception has occurred: module 'tensorflow' has no attribute 'get_default_graph'
  at Initialize
    self.graph = tf.get_default_graph()
   at Python.Runtime.PythonException.ThrowLastAsClrException()
   at Python.Runtime.PyObject.Invoke(PyTuple args in main.py: line 232
 module 'tensorflow' has no attribute 'get_default_graph'
2024-02-14T05:34:44.2701602Z TRACE:: JOB HANDLERS:
         DataFeed:             QuantConnect.Lean.Engine.DataFeeds.FileSystemDataFeed
         Setup:                QuantConnect.Lean.Engine.Setup.BacktestingSetupHandler
         RealTime:             QuantConnect.Lean.Engine.RealTime.BacktestingRealTimeHandler
         Results:              QuantConnect.Lean.Engine.Results.BacktestingResultHandler
         Transactions:         QuantConnect.Lean.Engine.TransactionHandlers.BacktestingTransactionHandler
         Object Store:         QuantConnect.Lean.Engine.Storage.LocalObjectStore
         History Provider:     QuantConnect.Lean.Engine.HistoricalData.HistoryProviderManager
         Brokerage:            QuantConnect.Brokerages.Backtesting.BacktestingBrokerage
         Data Provider:        QuantConnect.Lean.Engine.DataFeeds.DefaultDataProvider

2024-02-14T05:34:44.2708190Z TRACE:: FileSystemDataFeed.Exit(): Start. Setting cancellation token...
2024-02-14T05:34:44.2726494Z TRACE:: FileSystemDataFeed.Exit(): Exit Finished.
2024-02-14T05:34:44.2732708Z TRACE:: BacktestingResultHandler.Exit(): starting...
2024-02-14T05:34:44.2976360Z TRACE:: BacktestingResultHandler.Exit(): Saving logs...
2024-02-14T05:34:44.3015953Z ERROR:: During the algorithm initialization, the following exception has occurred: module 'tensorflow' has no attribute 'get_default_graph'
  at Initialize
    self.graph = tf.get_default_graph()
   at Python.Runtime.PythonException.ThrowLastAsClrException()
   at Python.Runtime.PyObject.Invoke(PyTuple args in main.py: line 232
 module 'tensorflow' has no attribute 'get_default_graph'
 module 'tensorflow' has no attribute 'get_default_graph'
  at Initialize
    self.graph = tf.get_default_graph()
   at Python.Runtime.PythonException.ThrowLastAsClrException()
   at Python.Runtime.PyObject.Invoke(PyTuple args in main.py: line 232
 module 'tensorflow' has no attribute 'get_default_graph'
2024-02-14T05:34:44.3019208Z TRACE:: Debug: 123
2024-02-14T05:34:44.3034927Z TRACE:: Debug: Your log was successfully created and can be retrieved from: /Results/1301725529-log.txt
2024-02-14T05:34:44.3038450Z TRACE:: BacktestingResultHandler.Run(): Ending Thread...
2024-02-14T05:34:44.3045069Z TRACE:: StopSafely(): Waiting for 'Result Thread' thread to stop...
2024-02-14T05:34:44.4306416Z TRACE:: 
STATISTICS:: OrderListHash d41d8cd98f00b204e9800998ecf8427e
2024-02-14T05:34:44.4310406Z TRACE:: BacktestingResultHandler.SendAnalysisResult(): Processed final packet
2024-02-14T05:34:44.4320373Z TRACE:: Engine.Run(): Disconnecting from brokerage...
2024-02-14T05:34:44.4325072Z TRACE:: Engine.Run(): Disposing of setup handler...
2024-02-14T05:34:44.4329319Z TRACE:: Engine.Main(): Analysis Completed and Results Posted.
2024-02-14T05:34:44.4342122Z TRACE:: StopSafely(): Waiting for '' thread to stop...
2024-02-14T05:34:44.4377055Z TRACE:: DataMonitor.GenerateReport():
DATA USAGE:: Total data requests 1
DATA USAGE:: Succeeded data requests 1
DATA USAGE:: Failed data requests 0
DATA USAGE:: Failed data requests percentage 0%
DATA USAGE:: Total universe data requests 0
DATA USAGE:: Succeeded universe data requests 0
DATA USAGE:: Failed universe data requests 0
DATA USAGE:: Failed universe data requests percentage 0%
2024-02-14T05:34:44.4492248Z TRACE:: Engine.Main(): Packet removed from queue: 1301725529
2024-02-14T05:34:44.4496848Z TRACE:: LeanEngineSystemHandlers.Dispose(): start...
2024-02-14T05:34:44.4504929Z TRACE:: LeanEngineSystemHandlers.Dispose(): Disposed of system handlers.
2024-02-14T05:34:44.4509541Z TRACE:: LeanEngineAlgorithmHandlers.Dispose(): start...
2024-02-14T05:34:44.4545524Z TRACE:: LeanEngineAlgorithmHandlers.Dispose(): Disposed of algorithm handlers.
